### ISSUE TITLE
QtCreator hangs with most recent plugin version

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dlangeditor#10]
QtCreator hangs whenever I try to open a D file in my project or use Ctrl+K to open the locator (commit `06b43e2e76ef9214649497b97b9910e6c58c7db1`). I've reproduced the error using an empty dub project (created through `dub init test`). When I rollback to a version before your code model changes everything is working fine again (commit `563283be2e7fe2e1b7d37a4129462399007fa348`)

**Comment by Groterik** [comment]
Thanks! Does it write something to console? I replaced some options for DCD that's why I think the problem is somewhere in settings. You should check it on options page.

**Comment by Groterik** [comment]
Oops, current version does not save and load DCD options properly. I'll fix it.

**Comment by stonemaster** [comment]
I'm sorry I didn't have time until now to investigate this problem any further. If you need more debug output or anything else, just let me know.

**Comment by Groterik** [comment]
Is it working now (from master)? Because for me it works. If not, please check your debug output and options.

**Comment by stonemaster** [comment]
Unfortunately it is still not working for me. Whenevery I try to open a D file Qtcreator hangs with this being the last output: 

```
~/Applications/qtcreator-3.3.1/bin$ ./qtcreator
[in]  "void startProcess(QProcess&, const QString&, const QStringList&, const QString&, QIODevice::OpenMode)"   "process=/usr/local/bin/dcd-server"
"/usr/local/bin/dcd-server"  process  ("--port", "9167")
[out]  "void startProcess(QProcess&, const QString&, const QStringList&, const QString&, QIODevice::OpenMode)"  time= 10
```

I see that a DCD server process is correctly started:
```
$ ps aux | grep dcd
astein   11936  0.0  0.0  20648  5668 pts/33   S+   11:17   0:00 /usr/local/bin/dcd-server --port 916
```

I'm on Kubuntu 14.10 using Qt Creator 3.3.1. My options also look sane:

![qtc-dcd](https://cloud.githubusercontent.com/assets/1463490/6573079/af736260-c717-11e4-8d3b-73f8681bb4e4.png)

**Comment by Groterik** [comment]
I have just pushed the fix. Please check it again.

**Comment by stonemaster** [comment]
Thanks for the fix! It is now working again.
