### ISSUE TITLE
Can't generate dub.json file

### ISSUE THREAD

**Issue by zoujiaqing** [Groterik/qtcreator-dlangeditor#21]
step one:
![qtcreator_create_app](https://cloud.githubusercontent.com/assets/444820/15955673/bdfcef42-2f15-11e6-8197-d1e6adda525c.png)

step two:
![qtcreator_dlang](https://cloud.githubusercontent.com/assets/444820/15955678/c6b322d2-2f15-11e6-95ed-38c5899da10b.png)

step three:
![qtcreator_non_dubfile](https://cloud.githubusercontent.com/assets/444820/15955680/cdbe9c28-2f15-11e6-96fc-1ca6e76cf611.png)\

quit Qt Creator show error:
![error](https://cloud.githubusercontent.com/assets/444820/15956897/1b77b816-2f1e-11e6-8342-55bce5005fa7.png)

**Comment by Groterik** [comment]
Should be fixed in [qtcreator-dubmanager](https://github.com/Groterik/qtcreator-dubmanager/commit/8bb2356aa9c68f1569b94df8b5b8f0fdd6cb1720).
