### ISSUE TITLE
Mac OSX Plugin fails to load

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dlangeditor#6]
I compiled the plugin for Mac OS X for the first time and unfortunately the plugins fails to load at startup giving me the following message:

```
Plugin initialization failed: Cannot open :/dlangeditor/DlangEditor.mimetypes.xml: Unknown error
```

The dubmanager plugin shows the same problem:

```
Plugin initialization failed: Cannot open :resources/DubProject.mimetypes.xml: Unknown error
```

Starting QtC on command line doesn't give any useful debug output.

**Comment by Groterik** [comment]
What versions are QtC and Qt?

**Comment by stonemaster** [comment]
Sorry I missed that important information. I have Qt 5.4 and Qt Creator 3.3.

**Comment by Groterik** [comment]
It seems like the plugins could not open Qt resource files (.qrc) during MIME types registration. The dlangeditor plugin tries to load resource files `Core::MimeDatabase::addMimeTypes(QLatin1String(":/dlangeditor/DlangEditor.mimetypes.xml")` that invokes the following code:
```C++
   QFile file(fileName);
    if (!file.open(QIODevice::ReadOnly|QIODevice::Text)) {
        *errorMessage = QString::fromLatin1("Cannot open %1: %2").arg(fileName, file.errorString());
        return false;
    }
```
And it fails on your machine with errorString = Unknown error. Why? I don't know. I believe that qrc loading itself is working well on Mac OS X (according to the http://doc.qt.io/qt-5/resources.html)
I searched for a solution a little:
1. Clean project and rebuild the plugins (http://stackoverflow.com/questions/21974054/qt-doesnt-recognize-existance-of-files-inside-qrc)
2. If it was useless, add "INCLUDEPATH += ." to .pro, clean, and rebuild the plugins (http://stackoverflow.com/questions/16250593/reading-from-and-writing-to-file-in-the-qt-resource-system-qt-5-0-2)
3. If it was useless, check for other plugins that can conflict by resource names (http://qt-project.org/forums/viewthread/9553)
Hope that helps. Looking forward to your reply.

**Comment by stonemaster** [comment]
Thank you for the detailed response! I tried 1 + 2. but unfortunately I'm still getting the same errors. I'll have a look at 3. but I doubt that I have clashes with resource names because I'm just using the standard plugins and the problem should then appear on other platforms too. Maybe I'll try compiling with an other Qt version too..

**Comment by stonemaster** [comment]
I tried compiling with Qt 5.3 and it didn't help too. Qt 5.2 leads to a crash at startup for some reason. Next I'll try to compile QtCreator from sources (and in debug mode) to see what's going on.

**Comment by Groterik** [comment]
Ok, keep me informed. I will try to find Mac OS X to check the plugins too.

**Comment by Groterik** [comment]
I tried the plugins under Mac OS X and requested some advice from qtcreator mail list. Waiting for response.

**Comment by Groterik** [comment]
I got the cause of issue from mailing list http://lists.qt-project.org/pipermail/qt-creator/2015-February/004394.html

The plugin tried to build against installed Qt framework (as it is configured in Qt toolchains in QtC) but QtC itself uses its own Qt libraries.
I have just added a simple script for fixing rpaths constants in *.dylib.

**Comment by stonemaster** [comment]
That's awesome! Thanks for your help and the fix for this problem. I am now able to start QtC normally. Unfortunately I run into a Dubmanager crash when trying to open a test D project:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtCore         	0x0000000108821c64 QString::operator=(QString const&) + 20
1   libDubProjectManager.dylib    	0x00000001117d8608 DubProjectManager::DubBuildStep::construct() + 88
2   libDubProjectManager.dylib    	0x00000001117d86af DubProjectManager::DubBuildStep::DubBuildStep(ProjectExplorer::BuildStepList*) + 95
3   libDubProjectManager.dylib    	0x00000001117dc7c3 DubProjectManager::DubBuildConfiguration::DubBuildConfiguration(ProjectExplorer::Target*, ProjectExplorer::BuildInfo const&) + 195
4   libDubProjectManager.dylib    	0x00000001117dd42b 
...
```

Which Qt version did you compile the plugin on Mac with?

**Comment by Groterik** [comment]
It is definitely the bug, but it seems like "dub" is not working. May be your path for "dub" is incorrect. Please, check your settings.

**Comment by stonemaster** [comment]
Hmm the problem is that there are no settings for dub?! In the preferences under D I am just able to specify settings for DCD but I can't an option to specify dub's path. dub is definitely working on my box because I created (and compiled) a test project with it. As dcd-server it is located under /usr/local/bin/. Is there some debug output or logging I could enable to get nearer this problem's root cause?

**Comment by Groterik** [comment]
The settings are here: "Build & Run" -> "DubManager".

**Comment by stonemaster** [comment]
Thanks for the info. I didn't know that configuration option. Indeed it was wrong but setting it to the right value (either to ```/usr/local/Cellar/dub/0.9.22/bin/dub``` or its symlink ```/usr/local/bin/dub```, tried both) it still crashes showing the same backtrace as before.. Unfortunately I currently have no working debug version of QtC (and somehow it fails to compile) to get more information out of the backtrace. Just compiling the D plugins in debug mode fails because of missing debug libraries.

**Comment by Groterik** [comment]
I have just added some errors handling and warning report messages (console and message-box). Please, try it.
https://github.com/Groterik/qtcreator-dubmanager/commit/5986f88c35314e9bb7125f692bdfe953bfdb73f8

**Comment by stonemaster** [comment]
It now crashes anymore and gives me the following very cryptic error message:

```
Dub process failed: Unknown error
Error at line: 5
Error at line: 5
Error at line: 5
Error executing command build: Expected valid json token, got '58posix,
    o'.
```

The dub.json file loaded (just a standard file generated from ```dub init```):

```
{
	"name": "testd",
	"description": "A minimal D application.",
	"copyright": "Copyright © 2015, stone",
	"authors": ["stone"],
	"dependencies": {
	}
}
```

The last line of dub --help returns ```DUB version unknown, built on Jan 13 2015```. The output is strange but brew says I have version 0.9.22.

**Comment by Groterik** [comment]
It is very strange. I have ```DUB version unknown, built on Feb  7 2015``` and brew says I have 0.9.22 too.
Could you please try to load project again and show me your console output with the words: ```Process failed:``?`. It will be the dub command with the arguments that cause the plugin failure. Also it will be great if you run that command in the project directory and show me the output (that the plugin can not parse as a json file).

**Comment by stonemaster** [comment]
It's getting even weirder: when I start Qt Creator from the command line I don't run into this issue at all. The project is then loaded just fine...

**Comment by Groterik** [comment]
Yep, I have no explanation. If you can not reproduce the issue from command line but it still is actual for "not from command line" it can be something wrong with your local QtC or/and DUB configuration.

**Comment by stonemaster** [comment]
Something seams totally broken on my system but as long as I have this workaround I am fine with it. At least it my be a good advice for anyone running into the same spooky problem :-)
